### ISSUE TITLE
备份库连接失败  500 Internal Server Error

### ISSUE THREAD

**Issue by ajie551** [myide/see#12]
[2019-03-28 18:17:53,310][MainThread:140695313114944][task_id:django.request][exception.py:118][ERROR][Internal Server Error: /api/sqlmng/inception/conncheck/]
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'inception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/seevenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/seevenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/seevenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/seevenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/seevenv/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/seevenv/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/seevenv/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/seevenv/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/seevenv/see-master/backend/sqlmng/views/settings.py", line 122, in post
    ret = func(self, request)
  File "/usr/local/seevenv/see-master/backend/sqlmng/mixins.py", line 95, in inception_backup
    password = self.conf.get('inception', 'inception_remote_system_password')
  File "/usr/local/python3.6/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/python3.6/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'inception'

**Comment by myide** [comment]
inception 安装了么？这是没找到它的配置文件
